// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD6kVkOOtVdfnVe506YLQgduTCndd11Ng',
    appId: '1:379439740902:web:1f188973cca43a90068827',
    messagingSenderId: '379439740902',
    projectId: 'exerlog-dy',
    authDomain: 'exerlog-dy.firebaseapp.com',
    databaseURL: 'https://exerlog-dy-default-rtdb.firebaseio.com',
    storageBucket: 'exerlog-dy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLfrut4geuL49gDT_5-39OvtzSvUOB6w4',
    appId: '1:379439740902:android:4ef542205c233786068827',
    messagingSenderId: '379439740902',
    projectId: 'exerlog-dy',
    databaseURL: 'https://exerlog-dy-default-rtdb.firebaseio.com',
    storageBucket: 'exerlog-dy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1zzUZEE6nOvVMmXt2BIcnfx9jIuD9nWU',
    appId: '1:379439740902:ios:12132929da47438a068827',
    messagingSenderId: '379439740902',
    projectId: 'exerlog-dy',
    databaseURL: 'https://exerlog-dy-default-rtdb.firebaseio.com',
    storageBucket: 'exerlog-dy.appspot.com',
    iosClientId: '379439740902-8r8p4h2gild5mc1v9qp736ji6e9pln3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.exerciseLog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1zzUZEE6nOvVMmXt2BIcnfx9jIuD9nWU',
    appId: '1:379439740902:ios:12132929da47438a068827',
    messagingSenderId: '379439740902',
    projectId: 'exerlog-dy',
    databaseURL: 'https://exerlog-dy-default-rtdb.firebaseio.com',
    storageBucket: 'exerlog-dy.appspot.com',
    iosClientId: '379439740902-8r8p4h2gild5mc1v9qp736ji6e9pln3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.exerciseLog',
  );
}
